### ISSUE TITLE
Homepage styling broken

### ISSUE THREAD

**Issue by pproe** [PubMedConnections/PubMedConnections#11]
Investigated this morning but couldn't find the reason my homepage was rendering like this:
![image](https://user-images.githubusercontent.com/40435390/190283664-bf466584-a3a8-40ef-960e-6280fd7ef356.png)

Suspect it's something to do with a styling conflict due to bootstrap being bootstrap, but couldn't locate the exact cause.

Happens on both Firefox and Chrome.

**Comment by Sothatsit** [comment]
Fixed now
