### ISSUE TITLE
'Max Graph Size' option does not limit size of rendered graph.

### ISSUE THREAD

**Issue by pproe** [PubMedConnections/PubMedConnections#12]
Steps to reproduce:
1.  Create graph with following options:
![image](https://user-images.githubusercontent.com/40435390/190287226-85054f37-4d8e-4253-930b-b217fac933c9.png)
2. Graph with 12,341 nodes will render (using Test Database)

**Comment by pproe** [comment]
Excuse me if I'm misunderstanding. Minimal knowledge of Neo4J and the backend in general, but as I can see the current flow counts the number of root authors that match the filter, raises an error (and returns 0 nodes) if the number exceeds the specified max graph size. 

Could you use [LIMIT](https://neo4j.com/docs/cypher-manual/current/clauses/limit/) here? To at least return the first x records.

Additionally, maybe we should make a change in the UI to highlight that the Max Graph Size option doesn't limit the total number of nodes but in fact the total number of 'root' nodes.

**Comment by pproe** [comment]
For some reason, graph rendering would halt if limit was set to a certain amount. This must have been a separate issue.

I think updating the UI in filter from 'Max Graph Size' -> 'Maximum Number of Root Nodes' or something more concise might not be a bad idea, just for clarity

**Comment by Sothatsit** [comment]
> For some reason, graph rendering would halt if limit was set to a certain amount. This must have been a separate issue.
> 
> I think updating the UI in filter from 'Max Graph Size' -> 'Maximum Number of Root Nodes' or something more concise might not be a bad idea, just for clarity

We should use a LIMIT on the number of returned nodes as well, we just don't yet. 

> Could you use [LIMIT](https://neo4j.com/docs/cypher-manual/current/clauses/limit/) here? To at least return the first x records.

I think returning data that isn't complete is confusing and maybe frustrating unless we explicitly say that the data has been truncated. I thought just returning an error would be simpler for the time being (although the error isn't displayed to users yet, it should print in the console).
