### ISSUE TITLE
Inconsistent error messages when no nodes exist.

### ISSUE THREAD

**Issue by pproe** [PubMedConnections/PubMedConnections#13]
When filtering a graph using a 'Author Name' string that doesn't return any nodes, the API returns a VisJS graph file with no content.

However, when filtering with a MeSH heading that doesn't return any values, it returns an specifying why there are no results. 

![image](https://user-images.githubusercontent.com/40435390/190297458-7829c105-faec-48bf-acf9-4a8ac10d0a55.png)

First request - Filtering using author name
Second request - Filtering using MeSH headings

**Comment by Sothatsit** [comment]
> When filtering a graph using a 'Author Name' string that doesn't return any nodes, the API returns a VisJS graph file with no content.
> 
> However, when filtering with a MeSH heading that doesn't return any values, it returns an specifying why there are no results.
> 
> ![image](https://user-images.githubusercontent.com/40435390/190297458-7829c105-faec-48bf-acf9-4a8ac10d0a55.png)
> 
> First request - Filtering using author name Second request - Filtering using MeSH headings

The MeSH headings are searched manually before being passed to Neo4J, so we can tell that the problem must be the MeSH heading not existing. Whereas, when there are multiple other filters, we wouldn't be able to distinguish between which of them caused the lack of results (unless there's only one, such as in this case). I can see how this could be inconsistent, although I thought if we were adding UI for displaying errors anyway, then this would help the user know why they got no results.

When there are no nodes, I'd imagine eventually we'll want to display a "No matching nodes" error anyway. Currently, the backend doesn't return that error itself, but just returns an empty result. Do you think it would be clearer if that error was returned from the backend as well?


Additionally, the `error_filter` was intended to allow us to highlight the filters that caused the error. I thought if we were to make any more complex filters, such as RegEx matching (just an example), then we could also display a similar error message if their RegEx pattern was invalid, for example.
