### ISSUE TITLE
'Unkown Filters present' When creating/fetching a new snapshot

### ISSUE THREAD

**Issue by pproe** [PubMedConnections/PubMedConnections#30]
Just putting this here for reference. Testing out analytic modal component and running into issues with generating the snapshot analytics.

Relevant message:
![image](https://user-images.githubusercontent.com/40435390/193286517-353872e5-21c0-4a0d-85e8-f0d9e7682864.png)

**Comment by pproe** [comment]
This is the data object returned from API, could be the cause of the issue (or just helpful in finding the root cause).

![image](https://user-images.githubusercontent.com/40435390/193288448-89fb4b2a-8b27-496e-a319-a95af49e2972.png)

**Comment by aaronnorrish** [comment]
> This is the data object returned from API, could be the cause of the issue (or just helpful in finding the root cause).
> 
> ![image](https://user-images.githubusercontent.com/40435390/193288448-89fb4b2a-8b27-496e-a319-a95af49e2972.png)

This bug has been fixed in commit [5da69be](https://github.com/PubMedConnections/PubMedConnections/pull/28/commits/5da69be208ad2d0aaaa5eae8d64542364114bbbb)
