### ISSUE TITLE
'Property Value too large to index' on data extraction

### ISSUE THREAD

**Issue by pproe** [PubMedConnections/PubMedConnections#31]
Running `extract` and it looks like neo4j cant handle this affiliation property.

Maybe there is more config changes that need to be made?

![image](https://user-images.githubusercontent.com/40435390/193365230-4b313b35-6858-430c-9211-058862fe230d.png)

**Comment by Sothatsit** [comment]
This should have been truncated, but it looks like it wasn't. Are you using an older version?
